# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQixDDr6RJ4uylnsX-KETGYvhsXWoopt
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np

# 1. Load dataset instantly from internal memory (No URL downloads, no path errors)
print("Loading built-in handwritten digits dataset...")
(X_train, y_train), (X_val, y_val) = tf.keras.datasets.mnist.load_data()

# Reshape data to include the single greyscale color channel
X_train = np.expand_dims(X_train, axis=-1)
X_val = np.expand_dims(X_val, axis=-1)

# Save our 10 class labels (digits 0 through 9) to a text file for the app UI
class_names = [str(i) for i in range(10)]
with open("classes.txt", "w") as f:
    for item in class_names: f.write(f"{item}\n")

# 2. Create an Ultra-Lightweight CNN Architecture
model = models.Sequential([
    layers.Input(shape=(28, 28, 1)),
    layers.Rescaling(1./255), # Fast inline bit-shifting pixel normalization

    layers.Conv2D(16, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(32, activation='relu'),
    layers.Dense(10, activation='softmax') # 10 nodes for digits 0-9
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 3. Rapid GPU Training Run (Only 2 epochs - takes ~30 seconds total)
print("Initiating rapid GPU neural network optimization...")
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=2, batch_size=64)

model.save('digit_classifier.keras')
print("\n🎉 Done! Model saved as 'digit_classifier.keras' and labels saved to 'classes.txt'")



# Commented out IPython magic to ensure Python compatibility.
# # 1. Write the Streamlit UI file script
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# import numpy as np
# from PIL import Image, ImageOps
# 
# st.title("🔢 Handwritten Digit AI Classifier")
# st.write("Upload a photo of a single drawn digit (0-9) to see the network guess it.")
# 
# model = tf.keras.models.load_model('digit_classifier.keras')
# with open("classes.txt", "r") as f: labels = [line.strip() for line in f.readlines()]
# 
# uploaded_file = st.file_uploader("Upload a drawing snippet...", type=["jpg", "jpeg", "png"])
# if uploaded_file is not None:
#     # Open, convert to greyscale, and resize exactly to 28x28 training matrix format
#     img = Image.open(uploaded_file).convert("L").resize((28, 28))
# 
#     # Invert colors if needed (MNIST dataset expects white writing on a black background)
#     st.image(img.resize((150, 150)), caption="Processed Input (28x28 Context View)")
# 
#     # Preprocess and execute prediction array matrix math
#     img_array = np.array(img)
#     img_array = np.expand_dims(img_array, axis=(0, -1)) # Set batch and channel dims
# 
#     preds = model.predict(img_array)
#     st.metric(label="Predicted Digit Value", value=labels[np.argmax(preds)])
# 
# # 2. Get local tunnel password and mount the web service
# import urllib.request
# print("\n--- 1. COPY THIS SPLASH SCREEN PASSWORD ---")
# print(urllib.request.urlopen('https://ident.me').read().decode('utf8'))
# print("-------------------------------------------\n")
# 
# print("--- 2. CLICK THIS LINK TO ACCESS YOUR WEB APP ---")
# !npm install -g localtunnel
# !streamlit run app.py & npx localtunnel --port 8501
#

import os
import tensorflow as tf
from tensorflow.keras import layers, models

# 1. Download official open-access TensorFlow Plant/Flower Dataset
print("Downloading optimized plant image dataset...")
_url = "https://googleapis.com"
path_to_tar = tf.keras.utils.get_file('flower_photos.tar.gz', origin=_url, extract=True)

# Point directly to where the subfolders are stored on the disk
DATA_DIR = os.path.join(os.path.dirname(path_to_tar), 'flower_photos')

# 2. Fast Streaming Data Loaders (180x180 pixels for rapid processing)
print("Setting up plant image loaders...")
train_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR, validation_split=0.2, subset="training", seed=123, image_size=(180, 180), batch_size=32)
val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR, validation_split=0.2, subset="validation", seed=123, image_size=(180, 180), batch_size=32)

# Save our categories to a text file for the web interface
class_names = train_ds.class_names
with open("classes.txt", "w") as f:
    for item in class_names: f.write(f"{item}\n")

# 3. Create a Fast, Modern CNN Architecture
model = models.Sequential([
    layers.Input(shape=(180, 180, 3)),
    layers.Rescaling(1./255), # Normalize pixel colors instantly

    layers.Conv2D(16, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(len(class_names), activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 4. Rapid GPU Training Run (Only 3 epochs to finish under 2 minutes)
print("Initiating rapid GPU plant model training...")
model.fit(train_ds, validation_data=val_ds, epochs=3)
model.save('plant_classifier.keras')
print("\n🎉 Success! Model saved as 'plant_classifier.keras' and labels saved to 'classes.txt'")

# Commented out IPython magic to ensure Python compatibility.
# # 1. Write the Streamlit application code file
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# import numpy as np
# from PIL import Image
# 
# st.title("🌿 Plant Species AI Dashboard")
# st.write("Upload a clear photo of a plant leaf or bloom to automatically recognize it.")
# 
# # Load the saved model artifacts
# model = tf.keras.models.load_model('plant_classifier.keras')
# with open("classes.txt", "r") as f: labels = [line.strip() for line in f.readlines()]
# 
# uploaded_file = st.file_uploader("Upload a plant/leaf image...", type=["jpg", "jpeg", "png"])
# if uploaded_file is not None:
#     img = Image.open(uploaded_file).convert("RGB").resize((180, 180))
#     st.image(img, caption="Target Upload Image", use_container_width=True)
# 
#     # Process matrix array and get classification label
#     img_array = np.expand_dims(np.array(img), axis=0)
#     preds = model.predict(img_array)
#     st.metric(label="Identified Plant Category", value=labels[np.argmax(preds)].upper())
# 
# # 2. Boot up the Streamlit server background process
# import subprocess
# subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])
# 
# # 3. EMBED THE APP DIRECTLY INSIDE COLAB (No external link needed!)
# from google.colab import output
# output.serve_kernel_port_as_iframe(8501, height='600')
#

# Commented out IPython magic to ensure Python compatibility.
# # 1. Write the Streamlit application code file
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# import numpy as np
# from PIL import Image
# 
# st.title("🌿 Plant Species AI Dashboard")
# st.write("Upload a clear photo of a plant leaf or bloom to automatically recognize it.")
# 
# # Load the saved model artifacts
# model = tf.keras.models.load_model('plant_classifier.keras')
# with open("classes.txt", "r") as f: labels = [line.strip() for line in f.readlines()]
# 
# uploaded_file = st.file_uploader("Upload a plant/leaf image...", type=["jpg", "jpeg", "png"])
# if uploaded_file is not None:
#     img = Image.open(uploaded_file).convert("RGB").resize((180, 180))
#     st.image(img, caption="Target Upload Image", use_container_width=True)
# 
#     # Process matrix array and get classification label
#     img_array = np.expand_dims(np.array(img), axis=0)
#     preds = model.predict(img_array)
#     st.metric(label="Identified Plant Category", value=labels[np.argmax(preds)].upper())
# 
# # 2. Boot up the Streamlit server background process
# import subprocess
# subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])
# 
# # 3. EMBED THE APP DIRECTLY INSIDE COLAB (No external link needed!)
# from google.colab import output
# output.serve_kernel_port_as_iframe(8501, height='600')
#

import os
import pathlib
import tensorflow as tf
from tensorflow.keras import layers, models

# 1. Download the flower dataset
print("Downloading plant data...")
_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
path_to_tar = tf.keras.utils.get_file('flower_photos', origin=_url, untar=True)
DOWNLOAD_DIR = pathlib.Path(path_to_tar)

# Ensure DATA_DIR points exactly to the directory containing the 5 category subfolders
if (DOWNLOAD_DIR / 'flower_photos').exists():
    DATA_DIR = DOWNLOAD_DIR / 'flower_photos'
else:
    DATA_DIR = DOWNLOAD_DIR

print(f"Target dataset directory: {DATA_DIR}")

# 2. Load training data with all classes detected
print("Reading images...")
train_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(180, 180),
    batch_size=32)

class_names = train_ds.class_names
print("Detected classes:", class_names)

# Save our correct category list to classes.txt for the UI and other evaluations
with open("classes.txt", "w") as f:
    for item in class_names:
        f.write(f"{item}\n")

# 3. Build the CNN targeting 5 output classes
model = models.Sequential([
    layers.Input(shape=(180, 180, 3)),
    layers.Rescaling(1./255),

    layers.Conv2D(16, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(len(class_names), activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 4. Train
print("Training model on all categories...")
model.fit(train_ds, epochs=3)
model.save("flower_model.keras")
print("\n🎉 Training finished! Model saved as 'flower_model.keras'")

import numpy as np
from google.colab import files

# 1. Load the validation split (the 20% the model never trained on)
val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(180, 180),
    batch_size=32)

# 2. Evaluate
loss, acc = model.evaluate(val_ds)
print(f"\nValidation accuracy: {acc*100:.1f}%")

# 3. Predict on your own flower photo
print("\nUpload a flower image (jpg/png):")
uploaded = files.upload()

for fname in uploaded.keys():
    img = tf.keras.utils.load_img(fname, target_size=(180, 180))
    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)   # make it a batch of 1

    preds = model.predict(img_array)[0]
    top = np.argmax(preds)
    print(f"\n{fname} -> {class_names[top]} ({preds[top]*100:.1f}% confident)")

# 4. Save the model
model.save("flower_model.keras")
print("\nModel saved as flower_model.keras")
files.download("flower_model.keras")

import numpy as np
import matplotlib.pyplot as plt

# Option A: test on a batch of validation images (never seen in training)
val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR, validation_split=0.2, subset="validation",
    seed=123, image_size=(180, 180), batch_size=32)

images, labels = next(iter(val_ds))
preds = model.predict(images)

plt.figure(figsize=(10, 10))
for i in range(9):
    plt.subplot(3, 3, i + 1)
    plt.imshow(images[i].numpy().astype("uint8"))
    pred = class_names[np.argmax(preds[i])]
    true = class_names[labels[i]]
    color = "green" if pred == true else "red"
    plt.title(f"Pred: {pred}\nTrue: {true}", color=color)
    plt.axis("off")
plt.tight_layout()
plt.show()

# Option B: test on a sunflower photo downloaded from the web
url = "https://storage.googleapis.com/download.tensorflow.org/example_images/592px-Red_sunflower.jpg"
img_path = tf.keras.utils.get_file("Red_sunflower", origin=url)

img = tf.keras.utils.load_img(img_path, target_size=(180, 180))
img_array = tf.expand_dims(tf.keras.utils.img_to_array(img), 0)
p = model.predict(img_array)[0]
top = np.argmax(p)

plt.imshow(img)
plt.title(f"{class_names[top]} ({p[top]*100:.1f}% confident)")
plt.axis("off")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import os
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay

# 1. Reload the correct TensorFlow Keras model to resolve naming collision
tf_model = tf.keras.models.load_model('flower_model.keras')

# 2. Extract actual class names from classes.txt
with open("classes.txt", "r") as f:
    actual_class_names = [line.strip() for line in f.readlines()]
print("Actual classes registered:", actual_class_names)

# 3. Load validation dataset with explicit labels
val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(180, 180),
    batch_size=32,
    class_names=actual_class_names,
    shuffle=False)

# 4. Collect true labels and predictions
y_true = np.concatenate([y.numpy() for _, y in val_ds])
y_prob = tf_model.predict(val_ds)
y_pred = np.argmax(y_prob, axis=1)

# 5. Build and plot the confusion matrix using explicit labels
cm = confusion_matrix(y_true, y_pred, labels=list(range(len(actual_class_names))))

fig, ax = plt.subplots(figsize=(7, 7))
ConfusionMatrixDisplay(cm, display_labels=actual_class_names).plot(
    ax=ax, cmap="Blues", xticks_rotation=45, colorbar=False)
plt.title("Flower classifier: confusion matrix")
plt.tight_layout()
plt.show()

# 6. Per-class precision / recall / F1
print(classification_report(y_true, y_pred, target_names=actual_class_names, labels=list(range(len(actual_class_names)))))

# Cell updated to use the re-isolated variables from the cell above
cm_normalized = confusion_matrix(y_true, y_pred, labels=list(range(len(actual_class_names))), normalize="true")

fig, ax = plt.subplots(figsize=(7, 7))
ConfusionMatrixDisplay(cm_normalized, display_labels=actual_class_names).plot(
    ax=ax, cmap="Blues", xticks_rotation=45, colorbar=False)
plt.title("Flower classifier: normalized confusion matrix")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.metrics import classification_report

# 1. Generate classification report dictionary, using zero_division=0 to handle empty classes safely
report_dict = classification_report(
    y_true,
    y_pred,
    target_names=actual_class_names,
    labels=list(range(len(actual_class_names))),
    output_dict=True,
    zero_division=0
)

# 2. Convert dictionary to pandas DataFrame and filter out metrics
report_df = pd.DataFrame(report_dict).iloc[:-1, :-3].T

# 3. Plot classification report as a Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(
    report_df,
    annot=True,
    cmap="Blues",
    fmt=".2f",
    linewidths=0.5,
    cbar=True,
    annot_kws={"size": 12}
)

plt.title("Flower Classifier Performance: Visual Classification Report", fontsize=15, pad=20)
plt.xlabel("Evaluation Metrics", fontsize=12, labelpad=10)
plt.ylabel("Flower Classes", fontsize=12)
plt.xticks(fontsize=11)
plt.yticks(rotation=0, fontsize=11)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def predict_flower(img_path):
    img = tf.keras.utils.load_img(img_path, target_size=(180, 180))
    arr = tf.expand_dims(tf.keras.utils.img_to_array(img), 0)
    p = model.predict(arr, verbose=0)[0]

    plt.imshow(img)
    plt.axis("off")
    plt.title(f"{class_names[np.argmax(p)]} ({p.max()*100:.1f}%)")
    plt.show()

    for name, prob in sorted(zip(class_names, p), key=lambda x: -x[1]):
        print(f"{name:12s} {prob*100:5.1f}%")

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

# 1. Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names

# Convert to DataFrame for visualization
df = pd.DataFrame(X, columns=feature_names)
df['species'] = [target_names[i] for i in y]
print("Dataset preview:")
display(df.head())

# 2. Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize and train a simple Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 4. Make predictions and evaluate
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"\nModel Accuracy: {accuracy * 100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=target_names))

