# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CK7WINz0a98Fk_pXCsqNBe9qYKftLqZX
"""

import time
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_curve, auc

!pip install -q datasets
from datasets import load_dataset

IMG, EPOCHS, N = 96, 5, 4000
class_names = ["cat", "dog"]

# 1. Load data (same source as before)
ds = load_dataset("microsoft/cats_vs_dogs", split="train", streaming=True).shuffle(seed=42, buffer_size=5000)
X, y = [], []
for ex in ds:
    try:
        img = ex["image"].convert("RGB").resize((IMG, IMG))
        X.append(np.array(img, dtype="float32") / 255.0)
        y.append(ex["labels"])
    except Exception:
        continue
    if len(X) >= N:
        break
X, y = np.array(X), np.array(y)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
print("Data:", X_train.shape, X_val.shape)

# 2. Define the two models
def simple_cnn():
    return tf.keras.Sequential([
        tf.keras.layers.Input((IMG, IMG, 3)),
        tf.keras.layers.Conv2D(32, 3, activation="relu"), tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Conv2D(64, 3, activation="relu"), tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Conv2D(128, 3, activation="relu"), tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ])

def mobilenet():
    base = tf.keras.applications.MobileNetV2(input_shape=(IMG, IMG, 3), include_top=False, weights="imagenet")
    base.trainable = False
    return tf.keras.Sequential([
        tf.keras.layers.Input((IMG, IMG, 3)),
        tf.keras.layers.Rescaling(2.0, offset=-1),   # [0,1] -> [-1,1] as MobileNetV2 expects
        base,
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ])

builders = {"Simple CNN": simple_cnn, "MobileNetV2": mobilenet}
models, histories, probs, rows = {}, {}, {}, []

# 3. Train and evaluate both
for name, build in builders.items():
    print(f"\n=== Training {name} ===")
    m = build()
    m.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    t0 = time.time()
    h = m.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=EPOCHS, batch_size=32, verbose=2)
    secs = time.time() - t0

    p = m.predict(X_val, verbose=0).ravel()
    pred = (p > 0.5).astype(int)
    fpr, tpr, _ = roc_curve(y_val, p)
    models[name], histories[name], probs[name] = m, h.history, (fpr, tpr)
    rows.append({"Model": name,
                 "Accuracy": accuracy_score(y_val, pred),
                 "F1": f1_score(y_val, pred),
                 "AUC": auc(fpr, tpr),
                 "Params": m.count_params(),
                 "Train time (s)": round(secs, 1)})

# 4. Comparison table + charts
df = pd.DataFrame(rows).set_index("Model")
print("\nMODEL COMPARISON")
print(df.round(3))

fig, ax = plt.subplots(1, 3, figsize=(18, 5))
for name, h in histories.items():
    ax[0].plot(h["val_accuracy"], label=f"{name} (val)")
    ax[1].plot(h["val_loss"], label=f"{name} (val)")
    fpr, tpr = probs[name]
    ax[2].plot(fpr, tpr, label=f"{name} AUC={df.loc[name, 'AUC']:.3f}")
ax[0].set_title("Validation Accuracy"); ax[0].set_xlabel("Epoch"); ax[0].legend()
ax[1].set_title("Validation Loss"); ax[1].set_xlabel("Epoch"); ax[1].legend()
ax[2].plot([0, 1], [0, 1], "k--"); ax[2].set_title("ROC Curves")
ax[2].set_xlabel("False Positive Rate"); ax[2].set_ylabel("True Positive Rate"); ax[2].legend()
plt.tight_layout(); plt.show()

df[["Accuracy", "F1", "AUC"]].plot(kind="bar", figsize=(7, 4), ylim=(0, 1), title="Metric Comparison")
plt.xticks(rotation=0); plt.show()

# 5. Prediction helper (both models)
def predict_image(pil_img):
    arr = np.array(pil_img.convert("RGB").resize((IMG, IMG)), dtype="float32") / 255.0
    out = {}
    for name, m in models.items():
        p = float(m.predict(arr[None], verbose=0)[0][0])
        label = class_names[int(p > 0.5)]
        conf = p if p > 0.5 else 1 - p
        out[name] = (label, conf)
    return out

def show_prediction(pil_img, title=""):
    res = predict_image(pil_img)
    txt = "\n".join(f"{n}: {l.upper()} ({c*100:.1f}%)" for n, (l, c) in res.items())
    plt.figure(figsize=(4, 4)); plt.imshow(pil_img); plt.axis("off")
    plt.title(f"{title}\n{txt}", fontsize=10); plt.show()

# 6a. Predict on your own image (upload a cat/dog photo)
from google.colab import files
print("\nUpload a cat or dog image (or cancel to skip)...")
try:
    uploaded = files.upload()
    for fname in uploaded:
        show_prediction(Image.open(fname), fname)
except Exception as e:
    print("Upload skipped:", e)

# 6b. Predict on 6 random validation images (shows true label too)
idx = np.random.choice(len(X_val), 6, replace=False)
fig, axs = plt.subplots(1, 6, figsize=(20, 4))
for a, i in zip(axs, idx):
    res = predict_image(Image.fromarray((X_val[i] * 255).astype("uint8")))
    a.imshow(X_val[i]); a.axis("off")
    a.set_title(f"Actual: {class_names[y_val[i]]}\n" +
                "\n".join(f"{n[:6]}: {l}" for n, (l, c) in res.items()), fontsize=9)
plt.tight_layout(); plt.show()

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

!pip install -q datasets
from datasets import load_dataset

IMG, EPOCHS, N = 64, 8, 4000
class_names = ["cat", "dog"]

# 1. Load data
ds = load_dataset("microsoft/cats_vs_dogs", split="train", streaming=True).shuffle(seed=42, buffer_size=5000)
X, y = [], []
for ex in ds:
    try:
        img = ex["image"].convert("RGB").resize((IMG, IMG))
        X.append(np.array(img, dtype="float32") / 255.0)
        y.append(ex["labels"])
    except Exception:
        continue
    if len(X) >= N:
        break
X, y = np.array(X), np.array(y)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
print("Loaded:", X.shape)

# 2. Build and train CNN
model = tf.keras.Sequential([
    tf.keras.layers.Input((IMG, IMG, 3)),
    tf.keras.layers.Conv2D(32, 3, activation="relu"), tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(64, 3, activation="relu"), tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(128, 3, activation="relu"), tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation="sigmoid"),
])
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=EPOCHS, batch_size=32)

# 3. Predictions
y_prob = model.predict(X_val).ravel()
y_pred = (y_prob > 0.5).astype(int)

# 4. Confusion matrix
cm = confusion_matrix(y_val, y_pred)
cm_pct = cm.astype("float") / cm.sum(axis=1, keepdims=True) * 100
print("Confusion matrix:\n", cm)

fig, ax = plt.subplots(1, 2, figsize=(11, 4.5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax[0],
            xticklabels=class_names, yticklabels=class_names)
ax[0].set_title("Confusion Matrix (counts)")
ax[0].set_xlabel("Predicted"); ax[0].set_ylabel("Actual")

sns.heatmap(cm_pct, annot=True, fmt=".1f", cmap="Greens", ax=ax[1],
            xticklabels=class_names, yticklabels=class_names)
ax[1].set_title("Confusion Matrix (% per actual class)")
ax[1].set_xlabel("Predicted"); ax[1].set_ylabel("Actual")
plt.tight_layout(); plt.show()

tn, fp, fn, tp = cm.ravel()
print(f"Cats correct (TN): {tn} | Cats called dogs (FP): {fp}")
print(f"Dogs called cats (FN): {fn} | Dogs correct (TP): {tp}")

print("\nCLASSIFICATION REPORT")
print(classification_report(y_val, y_pred, target_names=class_names))